"""Export market_events table to SQL for VPS import."""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from ml_service.db import fetch_all

OUT = ROOT / "deploy" / "market_events_seed.sql"


def _sql_value(val) -> str:
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "TRUE" if val else "FALSE"
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, dict):
        return f"'{json.dumps(val).replace(chr(39), chr(39)+chr(39))}'::jsonb"
    text = str(val).replace("'", "''")
    return f"'{text}'"


def main() -> int:
    OUT.parent.mkdir(exist_ok=True)
    rows = fetch_all(
        """
        SELECT asset, event_timestamp, snapshot_json, embedding::text AS embedding,
               actual_price_24h, actual_change_pct
        FROM market_events
        ORDER BY asset, event_timestamp
        """
    )
    if not rows:
        print("No market_events rows to export")
        return 1

    lines = [
        "-- RAG seed data generated by scripts/export_rag.py",
        "-- Run on VPS after ml_schema.sql has created market_events table",
        "BEGIN;",
        "TRUNCATE market_events RESTART IDENTITY;",
    ]
    for row in rows:
        cols = [
            "asset",
            "event_timestamp",
            "snapshot_json",
            "embedding",
            "actual_price_24h",
            "actual_change_pct",
        ]
        values = [
            _sql_value(row["asset"]),
            _sql_value(row["event_timestamp"]),
            _sql_value(row["snapshot_json"]),
            f"'{row['embedding']}'::vector",
            _sql_value(row["actual_price_24h"]),
            _sql_value(row["actual_change_pct"]),
        ]
        lines.append(
            f"INSERT INTO market_events ({', '.join(cols)}) VALUES ({', '.join(values)});"
        )
    lines.append("COMMIT;")
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Exported {len(rows)} rows to {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
